micronaut:
  application:
    name: mn-control-api
  jackson:
    bean-introspection-module: true
  router:
    versioning:
      enabled: true
      default-version: 1
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:54320/postgres?ssl=false;`}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:password}
jpa:
  default:
    packages-to-scan:
      - 'mx.com.burodecredito.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
endpoints:
  all:
    enabled: true
    sensitive: false
  stop:
    enabled: false